services:
  - type: web
    name: scholartrack-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn scholartrack.wsgi:application
    envVars:
      DJANGO_SETTINGS_MODULE: scholartrack.settings
      DATABASE_URL: ""
